/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */

/*
 * qsub_sup.c
 *
 *  Created on: Jul 3, 2020
 *      Author: bhagatr
 */


#include <pbs_config.h> /* the master config generated by configure */
#include <pbs_version.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/utsname.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <errno.h>
#include <fcntl.h>
#include <netdb.h>
#include <signal.h>
#include <termios.h>
#include <assert.h>
#include <sys/un.h>
#include <syslog.h>
#include "pbs_ifl.h"
#include "cmds.h"
#include "libpbs.h"
#include "net_connect.h"
#include "dis.h"
#include "port_forwarding.h"
#include "credential.h"

#if defined(HAVE_SYS_IOCTL_H)
#include <sys/ioctl.h>
#endif /* HAVE_SYS_IOCTL_H */
#define X11_PORT_LEN 8 /* Max size of buffer to store port information as string */

int		X11_comm_sock; /* Socket for x11 communication */
extern int	comm_sock; /* Socket for interactive and block job */
extern int	cs_init; 
extern char	*display; /* environment variable DISPLAY */
extern int	comm_sock; /* Socket for interactive and block job */
extern int	Forwardx11_opt;
extern char	*new_jobname; /* return from submit request */
extern char	server_out[PBS_MAXSERVERNAME + PBS_MAXPORTNUM + 2]; /* Destination server, parsed from destination[] */
static struct termios oldtio; /* Terminal info */
static struct winsize wsz; /* Window size */
extern		char *progname;
static		char msgbuf[MAXBUFLEN];

/**
 * @brief
 *	exit_qsub - issues the exit system call with the "exit" argument after
 * 	doing and needed library shutdown.
 *
 * @param[in] exitstatus integer value indiacting exit
 *
 * @return None
 *
 */
void
exit_qsub(int exitstatus)
{
/* A thread that makes qsub exit, should try and acquire the Critical Section. */
	critical_section();

	if (cs_init == 1)
		/* Cleanup security library initializations before exiting */
		CS_close_app();

#ifdef BACKTRACE_SIZE
	if (exitstatus != 0) {
		int i, frames;
		void *bt_buf[BACKTRACE_SIZE];
		char **bt_strings;

		frames = backtrace(bt_buf, BACKTRACE_SIZE);
		printf("Backtrace has %d frames.\n", frames);
		bt_strings = backtrace_symbols(bt_buf, frames);
		if (bt_strings == NULL) {
			printf("No backtrace symbols present!\n");
		} else {
			for (i=0; i < frames; i++) {
				printf("%s\n", bt_strings[i]);
			}
			free(bt_strings);
		}
	}
#endif

	exit(exitstatus);
}

/**
 * @brief
 *	This function creates a socket to listen for "X11" data
 *	and returns a port number where its listening for X data.
 *
 * @return	char*
 * @retval	portstring	success
 *
 * @par Side Effects
 *		If this function fails, it will exit the qsub process.
 *
 */
char *
port_X11(void)
{
	pbs_socklen_t namelen;
	struct sockaddr_in myaddr;
	static char X11_port_str[X11_PORT_LEN];
	unsigned short X11_port;

	X11_comm_sock = socket(AF_INET, SOCK_STREAM, 0);
	if (X11_comm_sock < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: unable to create socket", progname);
		perror(msgbuf);
		exit_qsub(1);
	}
	myaddr.sin_family = AF_INET;
	myaddr.sin_addr.s_addr = INADDR_ANY;
	myaddr.sin_port = 0;

	if (bind(X11_comm_sock, (struct sockaddr *) &myaddr,
		sizeof(myaddr)) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: unable to bind to socket", progname);
		perror(msgbuf);
		exit_qsub(1);
	}
	/* get port number assigned */
	namelen = sizeof(myaddr);
	if (getsockname(X11_comm_sock, (struct sockaddr *) &myaddr,
		&namelen) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: unable to get port number", progname);
		perror(msgbuf);
		exit_qsub(1);
	}
	X11_port = ntohs(myaddr.sin_port);
	(void) sprintf(X11_port_str, "%u", (unsigned int) X11_port);
	if (listen(X11_comm_sock, 1) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: listening on X11 socket failed", progname);
		perror(msgbuf);
		exit_qsub(1);
	}
	return (X11_port_str);
}

/**
 * @brief       This is a reader function which reads from the remote socket
 *              when X forwarding is enabled and writes it back to stdout.
 *
 * @param[in] s - socket descriptor from where data is to be read.
 *
 * @return	int
 * @retval	 0	Success
 * @retval	-1	Failure
 * @retval      -2      Peer Closed connection
 *
 */
int
reader_Xjob(int s)
{
	static char buf[PF_BUF_SIZE];
	int c = 0;
	char *p;
	int wc;
	int d = fileno(stdout);

	/* read from the socket and write to stdout */
	c = CS_read(s, buf, sizeof(buf));
	if (c > 0) {
		p = buf;
		while (c) {
			/*write data back to stdout*/
			if ((wc = write(d, p, c)) < 0) {
				if (errno == EINTR) {
					continue;
				} else {
					snprintf(msgbuf, sizeof(msgbuf), "%s: write error", progname);
					perror(msgbuf);
					return (-1);
				}
			}
			c -= wc;
			p += wc;
		}
	} else if (c == 0) {
		/*
		 * If control reaches here, then it means peer has closed the
		 * connection.
		 */
		return (-2);
	} else if (errno == EINTR) {
		return (0);
	} else {
		snprintf(msgbuf, sizeof(msgbuf), "%s: read error", progname);
		perror(msgbuf);
		return (-1);
	}

	return (0);
}

/**
 * @brief
 *	Interactive Reader process: reads from the remote socket,
 *	and writes that out to the stdout
 *
 * @param[in] s - socket (file descriptor)
 *
 * @return   Error code
 * @retval  -1  Failure
 * @retval   0   Success
 *
 */
int
reader(int s)
{
	char buf[4096];
	int c;
	char *p;
	int wc;

	/* read from the socket, and write to stdout */
	while (1) {
		c = CS_read(s, buf, sizeof(buf));
		if (c > 0) {
			p = buf;
			while (c) {
				if ((wc = write(1, p, c)) < 0) {
					if (errno == EINTR) {
						continue;
					} else {
						snprintf(msgbuf, sizeof(msgbuf), "%s: write error", progname);
						perror(msgbuf);
						return (-1);
					}
				}
				c -= wc;
				p += wc;
			}
		} else if (c == 0) {
			return (0); /* EOF - all done */
		} else {
			if (errno == EINTR)
				continue;
			else {
				snprintf(msgbuf, sizeof(msgbuf), "%s: read error", progname);
				perror(msgbuf);
				return (-1);
			}
		}
	}
}

/**
 * @brief
 * 	settermraw - set terminal into "raw" mode
 *
 * @param[in] ptio - pointer to termios structure
 *
 * @return None
 * @retval Void
 *
 */
void
settermraw(struct termios *ptio)
{
	struct termios tio;

	tio = *ptio;

	tio.c_lflag &= ~(ICANON|ISIG|ECHO|ECHOE|ECHOK);
	tio.c_iflag &= ~(IGNBRK|INLCR|ICRNL|IXON|IXOFF);
	tio.c_oflag = 0;
	tio.c_oflag |= (OPOST); /* TAB3 */
	tio.c_cc[VMIN] = 1;
	tio.c_cc[VTIME] = 0;

#if defined(TABDLY) && defined(TAB3)
	if ((tio.c_oflag & TABDLY) == TAB3)
		tio.c_oflag &= ~TABDLY;
#endif
	tio.c_cc[VKILL] = -1;
	tio.c_cc[VERASE] = -1;

	if (tcsetattr(0, TCSANOW, &tio) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: set terminal mode", progname);
		perror(msgbuf);
	}
}

/**
 * @brief
 * 	stopme - suspend process on ~^Z or ~^Y
 *	on suspend, reset terminal to normal "cooked" mode;
 *	when resumed, again set terminal to raw.
 *
 * @param[in] p - process id
 *
 * @return None
 * @retval Void
 *
 */
void
stopme(pid_t p)
{
	(void)tcsetattr(0, TCSANOW, &oldtio); /* reset terminal */
	kill(p, SIGTSTP);
	settermraw(&oldtio); /* back to raw when we resume */
}

/**
 * @brief
 * 	Writer process: reads from stdin, and writes
 * 	data out to the rem socket
 *
 * @param[in] s - file descriptor
 *
 * @return Void
 *
 */
void
writer(int s)
{
	char c;
	int i;
	int newline = 1;
	char tilde = '~';
	int wi;

	/* read from stdin, and write to the socket */

	while (1) {
		i = read(0, &c, 1);
		if (i > 0) { /* read data */
			if (newline) {
				if (c == tilde) { /* maybe escape character */

					/* read next character to check */

					while ((i = read(0, &c, 1)) != 1) {
						if ((i == -1) && (errno == EINTR))
							continue;
						else
							break;
					}
					if (i != 1)
						break;
					if (c == '.') /* termination character */
						break;
					else if (c == oldtio.c_cc[VSUSP]) {
						stopme(0); /* ^Z suspend all */
						continue;
#ifdef VDSUSP
					} else if (c == oldtio.c_cc[VDSUSP]) {
						stopme(getpid());
						continue;
#endif /* VDSUSP */
					} else { /* not escape, write out tilde */
						while ((wi = CS_write(s, &tilde, 1)) != 1) {
							if ((wi == -1) && (errno == EINTR))
								continue;
							else
								break;
						}
						if (wi != 1)
							break;
					}
				}
				newline = 0; /* no longer at start of line */
			} else {
				/* reset to newline if \n \r kill or interrupt */
				newline = (c == '\n') ||
					(c == oldtio.c_cc[VKILL]) ||
				(c == oldtio.c_cc[VINTR]) ||
				(c == '\r') ;
			}
			while ((wi = CS_write(s, &c, 1)) != 1) { /* write out character */
				if ((wi == -1) && (errno == EINTR))
					continue;
				else
					break;
			}
			if (wi != 1)
				break;

		} else if (i == 0) { /* EOF */
			break;
		} else if (i < 0) { /* error */
			if (errno == EINTR)
				continue;
			else {
				snprintf(msgbuf, sizeof(msgbuf), "%s: set terminal mode", progname);
				perror(msgbuf);
				return;
			}
		}
	}
	return;
}


/**
 * @brief
 *	strdup_esc_commas - duplicate a string escaping commas
 *	The string is duplicated with all commas in the original string
 *	escaped by preceding escape character.
 *
 * @param[in] str_to_dup - string to be duplicated
 *
 * @return
 * @retval string Succes
 * @retval NULL   Failure
 */
char *
strdup_esc_commas(char *str_to_dup)
{
	char *roaming = str_to_dup;
	char *endstr, *returnstr;

	if (str_to_dup == NULL)
		return NULL;

	returnstr = endstr = malloc(strlen(str_to_dup)*2 + 2);
	/* even for an all-comma string, this should suffice */
	if (returnstr == NULL)
		return NULL; /* just return null on malloc failure */
	while (*roaming != '\0') {
		while (*roaming != '\0' && *roaming != ',')
			*(endstr++) = *(roaming++);
		if (*roaming == ',') {
			*(endstr++) = ESC_CHAR;
			*(endstr++) = ',';
			roaming++;
		}
	}
	*endstr = '\0';
	return (returnstr);
}

/**
 * @brief
 * 	send_term - send the current TERM type and certain control characters
 *
 * @param[in] sock - file descriptor
 *
 * @return Void
 *
 */
void
send_term(int sock)
{
	char buf[PBS_TERM_BUF_SZ];
	char *term;
	char cc_array[PBS_TERM_CCA];

	term = getenv("TERM");
	term = strdup_esc_commas(term);
	if (term == NULL)
		snprintf(buf, sizeof(buf), "TERM=unknown");
	else {
		snprintf(buf, sizeof(buf), "TERM=%s", term);
		free(term);
	}
	(void)CS_write(sock, buf, PBS_TERM_BUF_SZ);

	cc_array[0] = oldtio.c_cc[VINTR];
	cc_array[1] = oldtio.c_cc[VQUIT];
	cc_array[2] = oldtio.c_cc[VERASE];
	cc_array[3] = oldtio.c_cc[VKILL];
	cc_array[4] = oldtio.c_cc[VEOF];
	cc_array[5] = oldtio.c_cc[VSUSP];
	CS_write(sock, cc_array, PBS_TERM_CCA);
}

/**
 * @brief
 *	send_winsize = send the current tty's window size
 *
 * @param[in] sock - file descriptor
 *
 * @return Void
 *
 */
void
send_winsize(int sock)
{
	char buf[PBS_TERM_BUF_SZ];

	(void)sprintf(buf, "WINSIZE %hu,%hu,%hu,%hu", wsz.ws_row, wsz.ws_col, wsz.ws_xpixel, wsz.ws_ypixel);
	(void)CS_write(sock, buf, PBS_TERM_BUF_SZ);
	return;
}

/**
 * @brief
 *	getwinsize - get the current window size
 *
 * @param[in] pwsz - pointer to winsize structure
 *
 * @return   Error code
 * @retval  -1    Failure
 * @retval   0    Success
 *
 */
int
getwinsize(struct winsize *pwsz)
{
	if (ioctl(0, TIOCGWINSZ, &wsz) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: unable to get window size", progname);
		perror(msgbuf);
		return (-1);
	}
	return (0);
}


/**
 * @brief
 *	catchchild = signal handler for Death of Child
 *
 * @param[in] sig - signal number
 *
 * @return Void
 *
 */
void
catchchild(int sig)
{
	int status;
	int pid;

	while (1) {
		pid = waitpid(-1, &status, WNOHANG|WUNTRACED);
		if (pid == 0)
			return;
		if ((pid > 0) && (WIFSTOPPED(status) == 0))
			break;
		if ((pid == -1) && (errno != EINTR)) {
			snprintf(msgbuf, sizeof(msgbuf), "%s:d status in catchchild:  ", progname);
			perror(msgbuf);
			return;
		}
	}

	/* reset terminal to cooked mode */

	(void)tcsetattr(0, TCSANOW, &oldtio);
	exit_qsub(0);
}

/**
 * @brief
 *	prints can't suspend qsub process on arrival of signal causing suspension
 *
 * @param[in] sig - signal number
 *
 * @return Void
 *
 */
void
no_suspend(int sig)
{
	printf("Sorry, you cannot suspend qsub until the job is started\n");
	fflush(stdout);
}

/**
 * @brief
 *	Shut and Close a socket
 *
 * @param	sock	file descriptor
 *
 * @return Void
 *
 */
void
shut_close_sock(int sock)
{
	shutdown(sock, 2);
	closesocket(sock);
}

/**
 * @brief
 * 	send delete job request, disconnect with server and exit qsub
 *
 * @param[in]	ret	qsub exit code
 *
 * @return      void
 *
 */
void
bailout(int ret)
{
	int c;

	shut_close_sock(comm_sock);
	printf("Job %s is being deleted\n", new_jobname);
	c = cnt2server(server_out);
	if (c <= 0) {
		fprintf(stderr,
			"%s: cannot connect to server %s (errno=%d)\n",
			progname, pbs_server, pbs_errno);
		exit_qsub(1);
	}
	(void)pbs_deljob(c, new_jobname, NULL);
	pbs_disconnect(c);
	exit_qsub(ret);
}

/**
 * @brief
 *	signal handler function for interrupt signal
 *
 * @param[in] sig - signal number
 *
 * @return Void
 *
 */
void
catchint(int sig)
{
	int c;

	printf("Do you wish to terminate the job and exit (y|[n])? ");
	fflush(stdout);
	while (1) {
		alarm(60); /* give a minute to think about it */
		c = getchar();

		if ((c == 'n') || (c == 'N') || (c == '\n'))
			break;
		else if ((c == 'y') || (c == 'Y') || (c == EOF)) {
			bailout(0);
		} else {
			printf("yes or no please\n");
			while ((c != '\n') && (c != EOF))
				c = getchar();
		}
	}
	alarm(0); /* reset alarm */
	while ((c != '\n') && (c != EOF))
		c = getchar();
	return;
}

/**
 * @brief
 *	signal handler for timeout scenario
 *
 * @param[in] sig - signal number
 *
 * @return Void
 *
 */
void
toolong(int sig)
{
	printf("Timeout -- deleting job\n");
	bailout(0);
}

/* The following functions support the "Interactive Job" capability of PBS. */

/**
 * @brief
 * 	interactive_port - get a socket to listen to for "interactive" job
 *	When the "interactive" job is run, its standard in, out, and error
 *	will be connected to this socket.
 *
 * @return string
 * @retval portstring holding port info
 * @note exits from program on failure
 *
 */
char *
interactive_port(void)
{
	pbs_socklen_t namelen;
	static char portstring[8];
	struct sockaddr_in myaddr;
	unsigned short port;

	if ((isatty(0) == 0) || (isatty(1) == 0)) {
		fprintf(stderr, "%s:\tstandard input and output must be a terminal for\n"
			"\tinteractive job submission\n", progname);
		exit_qsub(1);
	}
	comm_sock = socket(AF_INET, SOCK_STREAM, 0);
	if (comm_sock < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: unable to obtain socket", progname);
		perror(msgbuf);
		exit_qsub(1);
	}
	myaddr.sin_family = AF_INET;
	myaddr.sin_addr.s_addr = INADDR_ANY;
	myaddr.sin_port = 0;
	if (bind(comm_sock, (struct sockaddr *)&myaddr, sizeof(myaddr)) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: unable to obtain socket", progname);
		perror(msgbuf);
		exit_qsub(1);
	}

	/* get port number assigned */

	namelen = sizeof(myaddr);
	if (getsockname(comm_sock, (struct sockaddr *)&myaddr, &namelen) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: unable to get port number", progname);
		perror(msgbuf);
		exit_qsub(1);
	}
	port = ntohs(myaddr.sin_port);
	(void)sprintf(portstring, "%u", (unsigned int)port);
	if (listen(comm_sock, 1) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: listen on interactive socket", progname);
		perror(msgbuf);
		exit_qsub(1);
	}

	return (portstring);
}

/**
 * @brief
 *  Function used to log port forwarding messages.
 *
 * @param[in] msg - error message to be logged
 *
 * @return Void
 *
 */
static void
log_cmds_portfw_msg(char *msg)
{
	fprintf(stderr, "%s\n", msg);
	(void)fflush(stderr);
	(void)fflush(stdout);
}


/**
 * @brief
 *	This function initializes pfwdsock structure and eventually
 *	calls port_forwarder.
 *
 * @param[in]	X_data_socket - socket descriptor used to read X data from mom
 *				port forwarders.
 * @param[in]	interactive_reader_socket - socket descriptor used to read
 *				interactive job data coming from mom writer.
 * @return	void
 *
 * @par Side Effects
 * 	On failure, the function will cause the qsub process to exit.
 *
 */
static void
x11handler(int X_data_socket, int interactive_reader_socket)
{
	int n;
	struct pfwdsock *socks;
	socks = calloc(sizeof(struct pfwdsock), NUM_SOCKS);
	if (!socks) {
		fprintf(stderr, "Calloc failed : out of memory\n");
		exit_qsub(1);
	}
	for (n = 0; n < NUM_SOCKS; n++) {
		(socks + n)->active = 0;
	}
	socks->sock = X_data_socket;
	socks->active = 1;
	socks->listening = 1;

	/* Try to open a socket for the local X server. */

	port_forwarder(socks, x11_connect_display, display, 0,
		interactive_reader_socket, reader_Xjob, log_cmds_portfw_msg);
}

/**
 * @brief
 *	interactive - set up for interactive communication with job
 *
 * @return      void
 *
 * @par Side Effects
 *	On failure, the function will cause the qsub process to exit.
 *
 */
void
interactive(void)
{
	int amt;
	char cur_server[PBS_MAXSERVERNAME + PBS_MAXPORTNUM + 2];
	pbs_socklen_t fromlen;
	char momjobid[PBS_MAXSVRJOBID + 1];
	int news;
	int nsel;
	char *pc;
	fd_set selset;

	struct sigaction act;
	struct sockaddr_in from;
	struct timeval timeout;
	struct winsize wsz;
	int child;
	int ret;

	/* disallow ^Z which hangs up MOM starting an interactive job */
	sigemptyset(&act.sa_mask);
	act.sa_handler = no_suspend;
	act.sa_flags = 0;
	if (sigaction(SIGTSTP, &act, NULL) < 0) {
		perror("sigaction(SIGTSTP)");
		exit_qsub(1);
	}

	/* Catch SIGINT and SIGTERM, and setup to catch Death of child */
	act.sa_handler = catchint;
	if ((sigaction(SIGINT, &act, NULL) < 0) ||
		(sigaction(SIGTERM, &act, NULL) < 0)) {
		perror("unable to catch signals");
		exit_qsub(1);
	}
	act.sa_handler = toolong;
	if ((sigaction(SIGALRM, &act, NULL) < 0)) {
		perror("cannot catch alarm");
		exit_qsub(2);
	}

	/* save the old terminal setting */
	if (tcgetattr(0, &oldtio) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s: unable to get terminal settings", progname);
		perror(msgbuf);
		exit_qsub(1);
	}

	/* Get the current window size, to be sent to MOM later */
	if (getwinsize(&wsz)) {
		/* unable to get actual values, set defaults */
		wsz.ws_row = 20;
		wsz.ws_col = 80;
		wsz.ws_xpixel = 0;
		wsz.ws_ypixel = 0;
	}

	printf("%s: waiting for job %s to start\n", progname, new_jobname);

	/* Accept connection on socket set up earlier */
	nsel = 0;
	while (nsel == 0) {
		FD_ZERO(&selset);
		FD_SET(comm_sock, &selset);
		timeout.tv_usec = 0;
		timeout.tv_sec = 30;
		nsel = select(FD_SETSIZE, &selset, NULL, NULL, &timeout);
		if (nsel == -1) {
			if (errno == EINTR)
				nsel = 0;
			else {
				snprintf(msgbuf, sizeof(msgbuf), "%s: select failed", progname);
				perror(msgbuf);
				exit_qsub(1);
			}
		}
		if (nsel == 0) {
			/* connect to server, status job to see if still there */
			if (!locate_job(new_jobname, server_out, cur_server)) {
				fprintf(stderr, "%s: job %s apparently deleted\n", progname, new_jobname);
				exit_qsub(1);
			}
		}

	}

	/* apparently someone is attempting to connect to us */

retry:
	fromlen = sizeof(from);
	if ((news = accept(comm_sock, (struct sockaddr *)&from, &fromlen)) < 0) {
		snprintf(msgbuf, sizeof(msgbuf), "%s:  accept error from Interactive socket ", progname);
		perror(msgbuf);
		exit_qsub(1);
	}

	/*
	 * When Mom connects we expect:
	 * first, to engage in an authentication activity
	 * second, mom sends the job id for us to verify
	 */

	ret = CS_client_auth(news);

	if ((ret != CS_SUCCESS) && (ret != CS_AUTH_USE_IFF)) {
		fprintf(stderr, "%s: failed authentication with execution host\n", progname);
		shutdown(news, 2);
		exit_qsub(1);
	}

	/* now verify the value of job id */

	amt = PBS_MAXSVRJOBID + 1;
	pc = momjobid;
	while (amt > 0) {
		int len = CS_read(news, pc, amt);
		if (len <= 0)
			break;
		pc += len;
		if (*(pc - 1) == '\0')
			break;
		amt -= len;
	}
	if (pc == momjobid) { /* no data read */
		shutdown(news, 2);
		close(news);
		goto retry;
	}

	if (strncmp(momjobid, new_jobname, PBS_MAXSVRJOBID) != 0) {
		fprintf(stderr, "%s: invalid job name from execution server\n", progname);
		shutdown(news, 2);
		exit_qsub(1);
	}

	/*
	 * got the right job, send:
	 *		terminal type as "TERM=xxxx"
	 *		window size as   "WINSIZE=r,c,x,y"
	 */
	send_term(news);
	send_winsize(news);

	printf("%s: job %s ready\n\n", progname, new_jobname);

	/* set SIGINT, SIGTERM processing to default */

	act.sa_handler = SIG_DFL;
	if ((sigaction(SIGINT, &act, NULL) < 0) ||
		(sigaction(SIGTERM, &act, NULL) < 0) ||
		(sigaction(SIGALRM, &act, NULL) < 0) ||
		(sigaction(SIGTSTP, &act, NULL) < 0)) {
		perror("unable to reset signals");
		exit_qsub(1);
	}

	child = fork();
	if (child == 0) {
		/* child process - start the reader function set terminal into raw mode */
		settermraw(&oldtio);

		if (Forwardx11_opt) {
			/*
			 * if forwardx11_opt is set call x11handler which
			 * will act as a reader as well as a port forwarder
			 */
			x11handler(X11_comm_sock, news);
		} else {
			/* call interactive job's reader */
			(void) reader(news);
		}
		/* reset terminal */
		tcsetattr(0, TCSANOW, &oldtio);
		printf("\n%s: job %s completed\n", progname, new_jobname);
		exit_qsub(0);

	} else if (child > 0) {
		/* parent - start the writer function */
		act.sa_handler = catchchild;
		if (sigaction(SIGCHLD, &act, NULL) < 0)
			exit_qsub(1);

		writer(news);

		/* all done - make sure the child is gone and reset the terminal */
		kill(child, SIGTERM);
		shutdown(comm_sock, SHUT_RDWR);
		close(comm_sock);

		tcsetattr(0, TCSANOW, &oldtio);
		printf("\n%s: job %s completed\n", progname, new_jobname);
		exit_qsub(0);
	} else {
		snprintf(msgbuf, sizeof(msgbuf), "%s: unable to fork", progname);
		perror(msgbuf);
		exit_qsub(1);
	}
}
