/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */

/**
 * @file	pbs_interact.c
 * @brief
 * 	pbs_interact - (PBS) send message to batch job
 *
 * @author	Terry Heidelberg
 * 			Livermore Computing
 *
 * @author	Bruce Kelly
 * 			National Energy Research Supercomputer Center
 *
 * @author	Lawrence Livermore National Laboratory
 * 			University of California
 */

#include "cmds.h"
#include "pbs_ifl.h"
#include <pbs_config.h>   /* the master config generated by configure */
#include <pbs_version.h>

char *progname = "pbs_interact";
int comm_sock;
int cs_init = 0;
struct attrl *attrib = NULL; /* Attribute list */
char *display; /* environment variable DISPLAY */
int Forwardx11_opt = FALSE;
extern char *interactive_port(void);
char *new_jobname = NULL; /* return from submit request */
char server_out[PBS_MAXSERVERNAME + PBS_MAXPORTNUM + 2]; /* Destination server, parsed from destination[] */
extern void interactive(void);

int
main(int argc, char **argv, char **envp) /* pbs_interact */
{
	int connect = 0;
	int any_failed = 0;
	char *portstr = NULL;
	int rc = 0;

	char job_id[PBS_MAXCLTJOBID];       /* from the command line */

	char job_id_out[PBS_MAXCLTJOBID];
	char rmt_server[MAXSERVERNAME];
	char host[PBS_MAXHOSTNAME + 1];
	int stat = 0;
	int located = FALSE;

	/*test for real deal or just version and exit*/

	PRINT_VERSION_AND_EXIT(argc, argv);

	if (initsocketlib())
		return 1;

	if (argc != 2) {
		static char usage[] =
			"usage: pbs_interact job_identifier...\n";
		static char usag2[] = "       pbs_interact --version\n";
		fprintf(stderr, "%s", usage);
		fprintf(stderr, "%s", usag2);
		exit(2);
	}

	pbs_strncpy(job_id, argv[1], sizeof(job_id));
	if (get_server(job_id, job_id_out, server_out)) {
		fprintf(stderr, "%s: illegally formed job identifier: %s\n", progname, job_id);
		exit(1); 
	}
	new_jobname = job_id_out;

	/*perform needed security library initializations (including none)*/

	if (CS_client_init() != CS_SUCCESS) {
		fprintf(stderr, "%s: unable to initialize security library.\n", progname);
		exit(2);
	}

cnt:	connect = cnt2server(server_out);
	if (connect <= 0) {
		fprintf(stderr, "%s: cannot connect to server %s (errno=%d)\n",
				progname, pbs_server, pbs_errno);
		exit(1);

	}

	portstr = interactive_port();
	if (portstr == NULL) {
		any_failed = pbs_errno;
		goto err;
	}

	if ((rc = gethostname(host, (sizeof(host) - 1))) == 0) {
		rc = get_fullhostname(host, host, (sizeof(host) - 1));
	}
	if (rc != 0) {
		fprintf(stderr, "%s: cannot get full local host name\n", progname);
		exit (3);
	}

	stat = pbs_inter_connect_job(connect, job_id_out, host, portstr, NULL);
	if (stat && (pbs_errno != PBSE_UNKJOBID)) {
		fprintf(stderr, "%s\n",  pbse_to_txt(stat));
		any_failed = pbs_errno;
		goto err;
	} else if (stat && (pbs_errno == PBSE_UNKJOBID) && !located) {
		located = TRUE;
		if (locate_job(job_id_out, server_out, rmt_server)) {
			pbs_disconnect(connect);
			strcpy(server_out, rmt_server);
			goto cnt;
		}
		prt_job_err(progname, connect, job_id_out);
		any_failed = pbs_errno;
		goto err;
	}

	interactive();

err:	pbs_disconnect(connect);

	/*cleanup security library initializations before exiting*/
	CS_close_app();

	exit(any_failed);
}
