/*
 * Copyright (C) 1994-2021 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */

/*
 * qsub_sup.c
 *
 *  Created on: Jul 3, 2020
 *      Author: bhagatr
 */


#include <pbs_config.h> /* the master config generated by configure */
#include <pbs_version.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/utsname.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <errno.h>
#include <fcntl.h>
#include <netdb.h>
#include <signal.h>
#include <termios.h>
#include <assert.h>
#include <sys/un.h>
#include <syslog.h>
#include <openssl/sha.h>
#include "pbs_ifl.h"
#include "cmds.h"
#include "libpbs.h"
#include "net_connect.h"
#include "dis.h"
#include "port_forwarding.h"
#include "credential.h"

#if defined(HAVE_SYS_IOCTL_H)
#include <sys/ioctl.h>
#endif /* HAVE_SYS_IOCTL_H */

#define MAXPIPENAME sizeof(((struct sockaddr_un *)0)->sun_path)
#define QSUB_DMN_TIMEOUT_SHORT 5
#define QSUB_DMN_TIMEOUT_LONG 60 /* timeout for qsub background process */
#define DMN_REFUSE_EXIT 7 /* return code when daemon can't serve a job and exits */
#define CMDLINE 3
#define XAUTH_LEN 512 /* Max size of buffer to store Xauth cookie length */
#define XAUTH_ERR_REDIRECTION "2>&1" /* redirection string used for xauth command */

#if !defined(PBS_NO_POSIX_VIOLATION)
	char GETOPT_ARGS[] = "a:A:c:C:e:fhIj:J:k:l:m:M:N:o:p:q:r:R:S:u:v:VW:XzP:";
#else
	char GETOPT_ARGS[] = "a:A:c:C:e:fhj:J:k:l:m:M:N:o:p:q:r:R:S:u:v:VW:zP:";
#endif /* PBS_NO_POSIX_VIOLATION */

char usage[]=
	"usage: qsub [-a date_time] [-A account_string] [-c interval]\n"
	"\t[-C directive_prefix] [-e path] [-f ] [-h ] [-I [-X]] [-j oe|eo] [-J X-Y[:Z]]\n"
	"\t[-k keep] [-l resource_list] [-m mail_options] [-M user_list]\n"
	"\t[-N jobname] [-o path] [-p priority] [-P project] [-q queue] [-r y|n]\n"
	"\t[-R o|e|oe] [-S path] [-u user_list] [-W otherattributes=value...]\n"
	"\t[-v variable_list] [-V ] [-z] [script | -- command [arg1 ...]]\n";

char read_script_msg[]=
	"Job script will be read from standard input. Submit with CTRL+D.\n";

extern struct attrl *attrib; /* Attribute list */
char fl[MAXPIPENAME]; /* the filename used as the pipe name */
extern char *new_jobname; /* return from submit request */
extern char server_out[PBS_MAXSERVERNAME + PBS_MAXPORTNUM + 2]; /* Destination server, parsed from destination[] */
extern char	*tmpdir; /* Path of temp directory in which to put the job script */
extern char	cred_name[32]; /* space to hold small credential name */
extern char	destination[PBS_MAXDEST]; /* Destination of the batch job, specified by q opt */
extern char	script_tmp[MAXPATHLEN + 1]; /* name of script file copy */
extern char	retmsg[MAXPATHLEN]; /* holds the message that background qsub process will send */
extern char	qsub_cwd[MAXPATHLEN + 1]; /* buffer to pass cwd to background qsub */
extern char	*basic_envlist; /* basic comma-separated environment variables list string */
extern char	*qsub_envlist; /* comma-separated variables list string */
extern char	*v_value; /* expanded variable list from v opt */
extern char	*cred_buf;
extern int	sd_svr; /* return from pbs_connect */
extern int	is_background;
extern size_t	cred_len;


extern int recv_attrl(void *s, struct attrl **attrib);
extern int recv_string(void *s, char *str);
extern int recv_dyn_string(void *s, char **strp);
extern int send_string(void *s, char *str);
extern int send_attrl(void *s, struct attrl *attrib);
extern int send_opts(void *s);
extern int recv_opts(void *s);
extern int do_submit2(char *rmsg);
extern int dosend(void *s, char *buf, int bufsize);
extern int dorecv(void *s, char *buf, int bufsize);
extern int do_dir(char *, int, char *, size_t);
extern int check_qsub_daemon(char *);
extern int Interact_opt;
extern int sig_happened;
extern void log_syslog(char *msg);
extern void exit_qsub(int exitstatus);
extern void qsub_free_attrl(struct attrl *attrib);
extern void bailout(int ret);
extern char *strdup_esc_commas(char *str_to_dup);
static char *X11_get_authstring(void);
extern void set_attr_error_exit(struct attrl **attrib, char *attrib_name, char *attrib_value);
extern char     *display; /* environment variable DISPLAY */
extern int Forwardx11_opt;
extern char *port_X11(void);
static void daemon_stuff(void);

/**
 * @brief
 * 	Log a simple message to syslog
 * 	To be used from the qsub background daemon
 *
 * @param[in]	msg - string to be logged
 *
 */
void
log_syslog(char *msg)
{
	openlog("qsub", LOG_PID | LOG_CONS | LOG_NOWAIT, LOG_USER);
	syslog(LOG_ERR, "%s", msg);
	closelog();
}

/**
 * @brief
 *	Helper function to get the pbs conf file path, and
 *	convert it to a string, later added to the filename
 *	(pipe or unix domain socket filename) that is used
 *	for communications between the front-end and
 *	background qsub processes.
 *	The path to the pbs conf file is converted to a string
 *	by replacing the slashes with underscore char.
 *	If PBS_CONF_FILE is not set, then an empty string is returned.
 *
 * @return - The string representing path to the pbs conf file
 *
 */
static char *
get_conf_path(void)
{
	char *cnf = getenv("PBS_CONF_FILE");
	/* static pointer so we can free heap memory from previous invocation of this function */
	static char *dup_cnf_path = NULL;
	char *p;

	if (cnf) {
		p = strdup(cnf);
		if (p) {
			free(dup_cnf_path);
			dup_cnf_path = p;
			while (*p) {
				if (*p == '/' || *p == ' ' || *p == '.')
					*p = '_';
				p++;
			}
		}
		return dup_cnf_path;
	} else if (dup_cnf_path) {
		return dup_cnf_path;
	} else {
		return "";
	}
}


/**
 * @brief
 *      Create a temporary file that will house the job script
 *
 * @param[in]	file	- Input file pointer
 * @param[out]  script	- Temp file location
 * @param[in]   prefix	- Prefix for PBS directives
 *
 * @return      int
 * @retval	-1 - Error processing qsub parameters
 * @retval      3 - Error writing script file
 * @retval      4 - Temp file creation failure
 * @retval      5 - Error reading input file
 * @retval      6 - Unexpected EOF on read
 */
int
get_script(FILE *file, char *script, char *prefix)
{
	char *sopt;
	int err = 0;
	int exec = FALSE;
	char tmp_name[MAXPATHLEN + 1];
	FILE *TMP_FILE;
	char *in;
	char *s_in = NULL;
	int s_len = 0;
	static char tmp_template[] = "pbsscrptXXXXXX";
	int fds;

	/*
	 * Note: Need to populate script variable as soon as temp file is created so it
	 * gets cleaned up in case of an error.
	 */
	snprintf(tmp_name, sizeof(tmp_name), "%s/%s", tmpdir, tmp_template);
	fds = mkstemp(tmp_name); /* returns file descriptor */
	if (fds != -1) {
		snprintf(script, MAXPATHLEN + 1, "%s", tmp_name);
		if ((TMP_FILE = fdopen(fds, "w+")) == NULL)
			err = 1;
	} else {
		err = 1;
	}

	if (err != 0) {
		perror("mkstemp");
		fprintf(stderr, "qsub: could not create/open tmp file %s for script\n", tmp_name);
		return (4);
	}

	while ((in = pbs_fgets_extend(&s_in, &s_len, file)) != NULL) {
		if (!exec && ((sopt = pbs_ispbsdir(s_in, prefix)) != NULL)) {
			if (fputs(in, TMP_FILE) < 0) {
				perror("fputs");
				fprintf(stderr,
					"qsub: error writing copy of script, %s\n", tmp_name);
				fclose(TMP_FILE);
				free(s_in);
				return (3);
			}
			/*
			 * Setting options from the job script will not overwrite
			 * options set on the command line. CMDLINE-1 means
			 * "one less than CMDLINE priority"
			 */
			if (do_dir(sopt, CMDLINE - 1, retmsg, MAXPATHLEN) != 0) {
				fprintf(stderr, "%s", retmsg);
				free(s_in);
				return (-1);
			}
		} else if (!exec && pbs_isexecutable(s_in)) {
			exec = TRUE;
		}
		if (fputs(in, TMP_FILE) < 0) {
			perror("fputs");
			fprintf(stderr, "qsub: error writing copy of script, %s\n",
				tmp_name);
			fclose(TMP_FILE);
			free(s_in);
			return (3);
		}
	}

	free(s_in);
	if (fclose(TMP_FILE) != 0) {
		perror(" qsub: copy of script to tmp failed on close");
		return (5);
	}
	if (ferror(file)) {
		fprintf(stderr, "qsub: error reading script file\n");
		return (5);
	}
	return (0);
}


/**
 * @brief
 *	signal handler to avoid race condition
 *
 * @param[in] sig - signal number
 *
 * @return Void
 *
 */
void
blockint(int sig)
{
	sig_happened = sig;
}

/**
 * @brief
 *  Enable X11 Forwarding (on Unix) if specified.
 */
void
enable_gui(void)
{
	char *x11authstr = NULL;
	if (Forwardx11_opt) {
		if (!Interact_opt) {
			fprintf(stderr, "qsub: X11 Forwarding possible only for interactive jobs\n");
			exit_qsub(1);
		}
		/* get the DISPLAY's auth protocol, hexdata, and screen number */
		if ((x11authstr = X11_get_authstring()) != NULL) {
			set_attr_error_exit(&attrib, ATTR_X11_cookie, x11authstr);
			set_attr_error_exit(&attrib, ATTR_X11_port, port_X11());
#ifdef DEBUG
			fprintf(stderr, "x11auth string: %s\n", x11authstr);
#endif
		} else {
			exit_qsub(1);
		}
	}
}


/**
 * @Brief
 *      This function returns a string that consists of the protocol getting
 *      used, the hex data and the screen number . This string will form the
 *      basis of X authentication . It will be passed as a job attribute to
 *      MOM.
 * @return char*
 * @retval authstring Success
 * @retval NULL Failure
 *
 */
static char *
X11_get_authstring(void)
{
	char line[XAUTH_LEN] = {'\0'};
	char command[XAUTH_LEN] = {'\0'};
	char protocol[XAUTH_LEN];
	char hexdata[XAUTH_LEN];
	char screen[XAUTH_LEN];
	char format[XAUTH_LEN];
	char *authstring = NULL;
	FILE *f;
	int got_data = 0, ret = 0;
	char *p;

	protocol[0] = '\0';
	hexdata[0] = '\0';
	screen[0] = '\0';

	sprintf(format, " %%*s %%%ds %%%ds ", XAUTH_LEN - 1, XAUTH_LEN - 1);

	p = strchr(display, ':');
	if (p == NULL) {
		fprintf(stderr, "qsub: Failed to get xauth data "
			"(check $DISPLAY variable)\n");
		return NULL;
	}

	/* Try to get Xauthority information for the display. */
	if (strncmp(display, "localhost", sizeof("localhost") - 1) == 0) {
		/*
		 * Handle FamilyLocal case where $DISPLAY does
		 * not match an authorization entry. For this we
		 * just try "xauth list unix:displaynum.screennum".
		 * "localhost" match to determine FamilyLocal
		 * is not perfect.
		 */
		ret = snprintf(line, sizeof(line), "%s list unix:%s %s",
			XAUTH_BINARY,
			p + 1,
			XAUTH_ERR_REDIRECTION);
		if (ret >= sizeof(line)) {
			fprintf(stderr, " qsub: line overflow\n");
			return NULL;
		}
	} else {
		ret = snprintf(line, sizeof(line), "%s list %.255s %s",
			XAUTH_BINARY,
			display,
			XAUTH_ERR_REDIRECTION);
		if (ret >= sizeof(line)) {
			fprintf(stderr, " qsub: line overflow\n");
			return NULL;
		}
	}
	snprintf(command, sizeof(command), "%s", line);

	if (p != NULL)
		p = strchr(p, '.');

	if (p != NULL)
		snprintf(screen, sizeof(screen), "%s", p + 1);
	else
		strcpy(screen, "0"); /* Should be safe because sizeof(screen) = XAUTH_LEN which is >= 2 */

#ifdef DEBUG
	fprintf(stderr, "X11_get_authstring: %s\n", line);
#endif
	f = popen(line, "r");
	if (f == NULL) {
		fprintf(stderr, "execution of '%s' failed, errno=%d \n", command, errno);
	} else if (fgets(line, sizeof(line), f) == 0) {
		fprintf(stderr, "cannot read data from '%s', errno=%d \n", command, errno);
	} else if (sscanf(line, format,
		protocol,
		hexdata) != 2) {
		fprintf(stderr, "cannot parse output from '%s'\n", command);
	} else {
		/* SUCCESS */
		got_data = 1;
	}

	if (f != NULL) {
		/*
		 * Check the return value of pclose to see if the command failed?
		 * In that case, the "line" read from stdout is probably an
		 * error message (since stderr is redirected to stdout) from the shell or xauth,
		 * so display that to the user.
		 */
		if (pclose(f) != 0) {
			fprintf(stderr, "execution of xauth failed: %s", line);
			return NULL;
		}
	}

	if (!got_data)
		/* FAILURE */
		return NULL;

	/**
	 * Allocate 4 additional bytes for the terminating NULL character for
	 * each of the strings inside malloc
	 */
	authstring = malloc(strlen(protocol) + strlen(hexdata) +
		strlen(screen) + 4);
	if (authstring == NULL) {
		/* FAILURE */
		fprintf(stderr, " qsub: Malloc Failed\n");
		return NULL;
	}
	sprintf(authstring, "%s:%s:%s",
		protocol,
		hexdata,
		screen);

	return (authstring);
}

/**
 * @brief
 *	Fork the current process. Call the daemon_stuff function in the
 *	child process which starts listening on the unix domain socket etc.
 *	The parent process continues out of this function and eventually
 *	returns back control to the calling shell.
 *
 * @param[in] fname  - The filename used for the communication pipe/socket for
 *                     the communication between background and forground qsub processes.
 * @param[in] handle - Handle to synchronization event between foreground and
 *                     background qsub processes.
 * @param[in] server - Target server name of NULL in case of default
 *
 * exits program on failure
 *
 */
void
do_daemon_stuff()
{
	int pid;

	pid = fork();
	if (pid == 0) {
		/*
		 * Try to become the session leader.
		 * If that fails, exit with a syslog message
		 */
		if (setsid() == -1) {
			log_syslog("setsid failed");
			exit(1);
		}

		/*
		 * Just close standard files. We don't want to
		 * be session leader or close all other files.
		 */
		(void) fclose(stdin);
		(void) fclose(stdout);
		(void) fclose(stderr);

		/* clear off all the attributes */
		qsub_free_attrl(attrib);
		attrib = NULL;
		free(v_value);
		v_value = NULL;
		free(basic_envlist);
		basic_envlist = NULL;
		free(qsub_envlist);
		qsub_envlist = NULL;

		/* set single threaded mode */
		pbs_client_thread_set_single_threaded_mode();

		/* set when background qsub is running */
		is_background = 1;
		daemon_stuff();
		/*
		 * Control should never reach here.
		 * Still adding an exit, so it does not traverse parent code.
		 */
		exit(1);
	}
}

/**
 * @brief
 *	Signal handler for SIGPIPE
 * @param[in]	sig - signal number
 * @return	void
 *
 */
void
exit_on_sigpipe(int sig)
{
	perror("qsub: SIGPIPE received, job submission interrupted.");
	exit_qsub(1);
}

/**
 * @brief
 *  Set the signal handlers.
 */
void
set_sig_handlers(void)
{
	/* Catch SIGPIPE on write() failures. */
	struct sigaction act;
	sigemptyset(&act.sa_mask);
	act.sa_handler = exit_on_sigpipe;
	act.sa_flags = 0;
	if (sigaction(SIGPIPE, &act, NULL) < 0) {
		perror("qsub: unable to catch SIGPIPE");
		exit_qsub(1);
	}
}

/**
 * @brief
 *	Send data of bufsize length to the peer. Used for communications
 * 	between the foreground and background qsub processes.
 *
 * @param[in]	s - pointer to the windows PIPE or Unix domain socket
 * @param[in]	buf - The buf to send data from
 * @param[in]	bufsize - The amount of data to send
 *
 * @return int
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
dosend(void *s, char *buf, int bufsize)
{
	int bytes = 0;
	int sock = (int) *((int *) s);
	int rc;
	char *p = buf;
	int remaining = bufsize;
	do {
		/*
		 * For systems with MSG_NOSIGNAL defined (e.g. Linux 2.2 and later),
		 * we use send() rather than write() in order to block the SIGPIPE
		 * that qsub would receive if the remote side closes the stream. For
		 * other systems, the exit_on_sigpipe() handler gets called.
		 */
		errno = 0;
#ifdef MSG_NOSIGNAL
		rc = send(sock, p, remaining, MSG_NOSIGNAL);
#else
		rc = write(sock, p, remaining);
#endif
		if (rc == -1)
			return -1;
		if (rc == 0)
			break;
		bytes += rc;
		p += rc;
		remaining -= rc;
	} while (bytes < bufsize);

	if (bytes != bufsize)
		return -1;
	return 0;
}

/**
 * @brief
 *	Receive data of bufsize length from the peer. Used for communications
 * 	between the foreground and background qsub processes.
 *
 * @param[in]	s - pointer to the windows PIPE or Unix domain socket
 * @param[in]	buf - The buf to receive data into
 * @param[in]	bufsize - The amount of data to read
 *
 * @return int
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
dorecv(void *s, char *buf, int bufsize)
{
	int bytes = 0;
	char *p = buf;
	int remaining = bufsize;
	int sock = *((int *) s);
	int rc;

	do {
		errno = 0;
		rc = read(sock, p, remaining);
		if (rc == -1)
			return -1;
		if (rc == 0)
			break;
		bytes += rc;
		p += rc;
		remaining -= rc;
	} while (bytes < bufsize);

	if (bytes != bufsize)
		return -1;
	return 0;
}

/**
 * @brief
 *	Sets the filename to be used for the unix domain socket based comm.
 *	This is formed by appending the UID and the target server name to the
 *	filename. The length of the string is restricted to the length of the
 *	global variable fl. This is fairly small (108 characters) for Linux.
 *
 * @param[out] fname - The filename in tmpdir that is used as the unix domain socket
 *			file.
 *
 */
void
get_comm_filename(char *fname)
{
	char *env_svr = getenv(PBS_CONF_SERVER_NAME);
	char *env_port = getenv(PBS_CONF_BATCH_SERVICE_PORT);
	char *psi_var = pbs_get_conf_var(PBS_CONF_SERVER_INSTANCES);
	int count = 0;
	char buf[LARGE_BUF_LEN];
	int len;
	unsigned char hash[SHA_DIGEST_LENGTH];
	int i;

	count = snprintf(fname, MAXPIPENAME, "%s/pbs_%.16s_%lu_%.8s_%.32s_%.16s_%.5s_%s",
		tmpdir,
		((server_out == NULL || server_out[0] == 0) ?
		"default" : server_out),
		(unsigned long int)getuid(),
		cred_name,
		get_conf_path(),
		env_svr ? env_svr : "",
		env_port ? env_port : "",
		psi_var ? psi_var : ""
		);

	if (count >= MAXPIPENAME) {
		count = snprintf(fname, MAXPIPENAME, "%s/pbs_", TMP_DIR);
		len = snprintf(buf, MAXPIPENAME, "%.16s_%lu_%.8s_%.32s_%.16s_%.5s_%s",
			 ((server_out == NULL || server_out[0] == 0) ? "default" : server_out),
			 (unsigned long int) getuid(),
			 cred_name,
			 get_conf_path(),
			 (env_svr == NULL) ? "" : env_svr,
			 (env_port == NULL) ? "" : env_port,
			 psi_var ? psi_var : "");

		if (len + count < MAXPIPENAME) {
			pbs_strncpy(fname + count, buf, MAXPIPENAME - count);
		} else {
			if (SHA1((const unsigned char *) buf, SHA_DIGEST_LENGTH, (unsigned char *) &hash)) {
				for (i = 0; i < SHA_DIGEST_LENGTH; i++)
					sprintf(buf + (i * 2), "%02x", hash[i]);
					
				buf[SHA_DIGEST_LENGTH*2] = 0;
			}
			pbs_strncpy(fname + count, buf, MAXPIPENAME - count);
		}
	}

	free(psi_var);
}

/**
 * @brief
 *	Check whether a unix domain socket file is available.
 *	That is an indication that a background qsub might already be running.
 *
 * @param[out]	fname - The filename used for the communication pipe/socket for
 *			the communication between background and forground
 *			qsub processes.
 *
 * @return int
 * @retval	0 - Not available
 * @retval	1 - available
 *
 */
int
check_qsub_daemon(char *fname)
{
	get_comm_filename(fname);
	if (access(fname, F_OK) == 0) {
		/* check if file is usable */
		return 1;
	}
	return 0;
}


/**
 * @brief
 *	The daemon_stuff Unix counterpart.
 *	It creates a unix domain socket server and starts listening on it.
 *	The umask is set to 077 so that the domain socket file is owned and
 *	accessible by the user executing qsub only. Once a client (foreground
 *	qsub) connects, it receives all the data from the foreground qsub and
 *	executes do_submit, on the pre-established connection to pbs_server.
 *	The connection to server was estiblished by the caller of this function
 *	by calling do_connect().
 *	This function also does a "select" wait on input of data from foreground
 *	qsub processes, and a close notification on the socket with pbs_server.
 *	The select breaks if foreground qsubs connect, the pbs_server dies, or
 *	the timeout of 1 minutes expires. For the latter two cases, this function
 *	does a silent exit of the background qsub daemon.
 *
 */
static void
daemon_stuff(void)
{
	int sock, bindfd;
	struct sockaddr_un s_un;
	struct sockaddr from;
	socklen_t fromlen;
	int rc;
	fd_set readset;
	fd_set workset;
	struct timeval timeout;
	int n, maxfd;
	mode_t cmask = 0077;
	time_t connect_time = time(0);
	sigset_t newsigmask, oldsigmask;
	char *err_op = "";
	char log_buf[LOG_BUF_SIZE];
	int cred_timeout = 0;
	svr_conn_t **svr_conns = get_conn_svr_instances(sd_svr);
	int i;

	/* set umask so socket file created is only accessible by same user */
	umask(cmask);
	sigemptyset(&newsigmask);
	sigaddset(&newsigmask, SIGPIPE);
	sigprocmask(SIG_BLOCK, &newsigmask, NULL);

	/* start up a unix domain socket to listen */
	if ((bindfd = socket(AF_UNIX, SOCK_STREAM, 0)) == -1) {
		err_op = "socket";
		goto error;
	}

	s_un.sun_family = AF_UNIX;
	snprintf(s_un.sun_path, sizeof(s_un.sun_path), "%s", fl);

	if (bind(bindfd, (const struct sockaddr *) &s_un, sizeof(s_un)) == -1)
		exit(1); /* dont go to error */

	FD_ZERO(&readset);
	if (listen(bindfd, 1) != 0) {
		err_op = "listen";
		goto error;
	}

	FD_SET(bindfd, &readset);
	for (i = 0; svr_conns[i]; i++)
		FD_SET(svr_conns[i]->sd, &readset);
	maxfd = (bindfd > sd_svr) ? bindfd : sd_svr;
	while (1) {

		err_op = "";

		memcpy(&workset, &readset, sizeof(readset));

		timeout.tv_usec = 0;
		/* since timeout gets reset on Linux */
		if (cred_timeout == 1)
			timeout.tv_sec = QSUB_DMN_TIMEOUT_SHORT; /* Short timeout to allow any foreground process to finsih before exiting */
		else
			timeout.tv_sec = QSUB_DMN_TIMEOUT_LONG;
		n = select(maxfd + 1, &workset, NULL, NULL, &timeout);
		if (n == 0)
			goto out; /* daemon timed out waiting for connect from foreground */
		else if (n == -1) {
			err_op = "select failed";
			goto error;
		}

		/*
		 * check if we are past the credential timeout
		 * Error out even if it is close to CREDENTIAL_LIFETIME, as
		 * request could take a while to reach server and get processed
		 * Qsub then does a regular submit (new connection)
		 */
		if (cred_timeout == 0 && ((time(0) - connect_time) > (CREDENTIAL_LIFETIME - QSUB_DMN_TIMEOUT_LONG))) {
			unlink(fl);
			cred_timeout = 1;
		}

		for (i = 0; svr_conns[i]; i++) {
			if (FD_ISSET(svr_conns[i]->sd, &workset)) {
				if (recv(svr_conns[i]->sd, &rc, 1, MSG_OOB) < 1)
					goto out;
			}
		}

		/* accept the connection */
		fromlen = sizeof(from);
		if ((sock = accept(bindfd, &from, &fromlen)) == -1) {
			err_op = "accept";
			goto error;
		}

		if ((recv_attrl(&sock, &attrib) != 0) ||
			(recv_string(&sock, destination) != 0) ||
			(recv_string(&sock, script_tmp) != 0) ||
			(recv_string(&sock, cred_name) != 0) ||
			(recv_dyn_string(&sock, &v_value) != 0) ||
			(recv_dyn_string(&sock, &basic_envlist) != 0) ||
			(recv_dyn_string(&sock, &qsub_envlist) != 0) ||
			(recv_string(&sock, qsub_cwd) !=0) ||
			(recv_opts(&sock) != 0)) {
			err_op = "recv data from foreground";
			goto error;
		}

		/*
		 * At this point the background qsub daemon has received all the data from the
		 * foreground. Lets tell the foreground that we have received the data, so that
		 * if the we crashed at any point after this the foreground should not end up
		 * submitting a duplicate job. However, if the foreground did not get this intimation,
		 * then it could go ahead and do a regular job submit.
		 */
		rc = 0;
		if (dosend(&sock, (char *) &rc, sizeof(int)) != 0) {
			err_op = "send data to foreground";
			goto error;
		}

		/* set the current work directory by doing a chdir */
		if (chdir(qsub_cwd) != 0) {
			err_op = "chdir";
			goto error;
		}

		if (setenv("PWD", qsub_cwd, 1) != 0) {
			err_op = "setenv";
			goto error;
		}

		sigemptyset(&newsigmask);
		sigaddset(&newsigmask, SIGXCPU);
		sigaddset(&newsigmask, SIGXFSZ);
		sigaddset(&newsigmask, SIGTSTP);
		sigaddset(&newsigmask, SIGINT);
		sigaddset(&newsigmask, SIGSTOP);
		sigaddset(&newsigmask, SIGTERM);
		sigaddset(&newsigmask, SIGTSTP);
		sigaddset(&newsigmask, SIGALRM);
		sigaddset(&newsigmask, SIGQUIT);
		sigaddset(&newsigmask, SIGUSR1);
		sigaddset(&newsigmask, SIGUSR2);
		sigprocmask(SIG_BLOCK, &newsigmask, &oldsigmask);

		rc = do_submit2(retmsg);

		if (send_string(&sock, retmsg) != 0) {
			err_op = "send data to foreground";
			goto error;
		}
		if (dosend(&sock, (char *) &rc, sizeof(int)) != 0) {
			err_op = "send data to foreground";
			goto error;
		}

		close(sock);
		sigprocmask(SIG_SETMASK, &oldsigmask, NULL);

		qsub_free_attrl(attrib);
		attrib = NULL;
		free(v_value);
		v_value = NULL;
		free(basic_envlist);
		basic_envlist = NULL;
		free(qsub_envlist);
		qsub_envlist = NULL;

		if (cred_buf != NULL) {
			memset(cred_buf, 0, cred_len);
			free(cred_buf);
			cred_buf = NULL;
		}

		/* Exit the daemon if it can't submit the job */
		if (rc == DMN_REFUSE_EXIT)
			goto out;
	}

out:
	close(bindfd);
	if (cred_timeout != 1)
		unlink(fl);
	exit(0);

error:
	sprintf(log_buf, "Background qsub: Failed at %s, errno=%d", err_op, errno);
	log_syslog(log_buf);
	unlink(fl);
	close(bindfd);
	exit(1);
}

/*
 * @brief
 *  Try to submit job through daemon. On Unix, the daemon would be created by
 *  forking during a prior invocation of the qsub command. The foregound qsub
 *  process tries to send the job to the daemon using Unix domain sockets.
 *
 * @param[out] daemon_up         - Indicate whether daemon is running
 * @param[out] do_regular_submit - Indicate whether to do regular submit
 * @param[in]  qsub_exe          - Name of the qsub command
 *
 * @return     rc                - Error code
 */
int
daemon_submit(int *daemon_up, int *do_regular_submit)
{
	int sock; /* UNIX domain socket for talking to daemon */
	struct sockaddr_un s_un;
	sigset_t newsigmask;
	int rc = 0;
again:
	/*
	 * In case of Unix, use fork. Foreground checks if connection is
	 * possible with background daemon. The communication used is unix
	 * domain sockets. Only the specified user can connect to this socket
	 * since the domain socket is created with a 0600 permission.
	 *
	 * If connection fails, proceed with qsub in the normal flow, and at
	 * the end fork and stay in the background, while the foreground
	 * process returns control to the shell. Subsequent qsubs will be able
	 * to connect to this forked background qsub.
	 *
	 */
	*daemon_up = check_qsub_daemon(fl);
	if (*daemon_up == 1) {
		/* pass information to daemon */
		/* wait for job-id or error string */
		if ((sock = socket(AF_UNIX, SOCK_STREAM, 0)) == -1)
			return rc;

		s_un.sun_family = AF_UNIX;
		snprintf(s_un.sun_path, sizeof(s_un.sun_path), "%s", fl);

		if (connect(sock, (const struct sockaddr *) &s_un, sizeof(s_un)) == -1) {
			int refused = (errno == ECONNREFUSED);

			close(sock);
			if (refused) {
				/* daemon unavailable, del temp file, restart */
				if (unlink(fl) != 0)
					return rc;

				goto again;
			}
			return rc;
		}

		/* block SIGPIPE on write() failures. */
		sigemptyset(&newsigmask);
		sigaddset(&newsigmask, SIGPIPE);
		sigprocmask(SIG_BLOCK, &newsigmask, NULL);

		if ((send_attrl(&sock, attrib) == 0) &&
			(send_string(&sock, destination) == 0) &&
			(send_string(&sock, script_tmp) == 0) &&
			(send_string(&sock, cred_name) == 0) &&
			(send_string(&sock, v_value?v_value:"") == 0) &&
			(send_string(&sock, basic_envlist) == 0) &&
			(send_string(&sock, qsub_envlist?qsub_envlist:"") == 0) &&
			(send_string(&sock, qsub_cwd) == 0) &&
			(send_opts(&sock) == 0)) {

			/*
			 * Read back the first error code from the background,
			 * which confirms whether the background received our data.
			 */
			if (dorecv(&sock, (char *) &rc, sizeof(int)) == 0) {
				/*
				 * We were able to send data to the background daemon.
				 * Now, even if we fail to read back response from
				 * background, we do not want to submit again.
				 */
				*do_regular_submit = 0;
			}

			/* read back response from background daemon */
			if ((recv_string(&sock, retmsg) != 0) ||
				(dorecv(&sock, (char *) &rc, sizeof(int)) != 0) ||
				rc == DMN_REFUSE_EXIT) {
				/*
				 * Something bad happened, either background submitted
				 * and failed to send us response, or it failed before
				 * submitting. If background qsub detects -V option, then
				 * submit the job through foreground.
				 */
				if (rc != DMN_REFUSE_EXIT) {
					rc = -1;
					sprintf(retmsg, "Failed to recv data from background qsub\n");
					/* Error message will be printed in caller */
				} else
					*do_regular_submit = 1;
			}
		}
		/* going down, no need to free stuff */
		close(sock);
	}

	return rc;
}
